"""Unit tests for the README SVG renderer — the SGR parser and escaping.

The SVG itself is regenerated by hand, so only the two pure functions and
the payload shape are pinned here.
"""
import json
import os
import sys
import unittest

sys.path.insert(0, "tests")
sys.path.insert(0, "src")
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tools"))

import render_svg  # noqa: E402


class Runs(unittest.TestCase):
    def test_plain_text_single_run(self):
        self.assertEqual(render_svg.runs("hello"), [("hello", "#a9b1d6", False)])

    def test_colour_run(self):
        line = "\x1b[38;2;169;177;214mhi\x1b[0m"
        self.assertEqual(render_svg.runs(line),
                         [("hi", "#a9b1d6", False)])

    def test_bold_run(self):
        self.assertEqual(render_svg.runs("\x1b[1mhi\x1b[0m"),
                         [("hi", "#a9b1d6", True)])

    def test_reset_restores_defaults(self):
        line = "\x1b[1;38;2;1;2;3mred\x1b[0mplain"
        self.assertEqual(render_svg.runs(line),
                         [("red", "#010203", True), ("plain", "#a9b1d6", False)])

    def test_empty_sequence_is_reset(self):
        self.assertEqual(render_svg.runs("\x1b[0m"), [])

    def test_24bit_parse(self):
        line = "\x1b[38;2;247;118;142mX"
        self.assertEqual(render_svg.runs(line), [("X", "#f7768e", False)])


class Esc(unittest.TestCase):
    def test_escapes_xml(self):
        self.assertEqual(render_svg.esc('a<b>&c'), "a&lt;b&gt;&amp;c")


class Payload(unittest.TestCase):
    def test_payload_shape(self):
        p = json.loads(render_svg.payload("ds4-pro-xhigh"))
        self.assertEqual(p["model"]["id"], "ds4-pro-xhigh")
        self.assertEqual(p["session_id"], "readme")


if __name__ == "__main__":
    unittest.main()
