// Code generated by cmd/genprofiles; DO NOT EDIT.
// Source: src/proxy.py PROFILES table.

package profiles

var generatedProfiles = []Profile{
	{Name: "direct", Port: 31500, Dir: "~/.claude-ds4", Upstream: "https://api.deepseek.com/anthropic", Model: "", ZDR: false, Spend: false, Inject: true, MaxOut: 65536, Failover: ""},
	{Name: "openrouter", Port: 31501, Dir: "~/.claude-or-ds4", Upstream: "https://openrouter.ai/api", Model: "deepseek/deepseek-v4-flash-0731:nitro", ZDR: true, Spend: true, Inject: false, MaxOut: 65536, Failover: ""},
	{Name: "nous", Port: 31502, Dir: "~/.claude-nous", Upstream: "https://inference-api.nousresearch.com", Model: "deepseek/deepseek-v4-flash-0731", ZDR: false, Spend: true, Inject: false, MaxOut: 65536, Failover: "direct"},
}
